ALTER TABLE rooms ADD COLUMN position_x FLOAT DEFAULT 0;
ALTER TABLE rooms ADD COLUMN position_y FLOAT DEFAULT 0;
ALTER TABLE rooms ADD COLUMN width FLOAT DEFAULT 10;
ALTER TABLE rooms ADD COLUMN height FLOAT DEFAULT 10;
